### ISSUE TITLE
eisengrind/altv-server:dev `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by FDiskas** [eisengrind/docker-altv-server#18] opened 2021-08-05 08:12 UTC
```
[11:02:53][Error] Failed to load "js-module.so", Unix error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /opt/altv/modules/js-module/libnode.so.83)
```

**Comment by FDiskas** [comment] 2021-08-05 09:12
Possible fix could be change docker from `debian:buster-slim` to `plentico/plenti` - but I don't trust that
https://github.com/plentico/plenti/issues/157

**Comment by pixlcrashr** [comment] 2021-08-05 09:27
Well, the issue is that libglibc is not installed on the image with the newest version.

As always, the alt:V team pushes things without announcing it - ¯\\_(ツ)_/¯

**Comment by pixlcrashr** [comment] 2021-08-05 10:01
Should be fixed after https://github.com/eisengrind/docker-altv-server/actions/runs/1101015193 has run.

Let me know if it works, then.

Btw. I changed the base image from `debian:buster-slim` to `ubuntu:focal-20210723` due to the fact that currently only Ubuntu Focal supports Glibc >= 2.29

**Comment by pixlcrashr** [comment] 2021-08-05 12:08
https://github.com/altmp/altv-issues/issues/1054 Should fix this - anyway - from now on we'll use Ubuntu focal for the Docker image.

**Comment by pixlcrashr** [comment] 2022-02-06 15:19
Since the Docker image now uses an Ubuntu image to support glibc >= 2.29 this issue can be closed. Also altmp/altv-issues#1054 was fixed.

**Closed as completed** 2022-02-06 15:20 UTC
Labels: bug
