### ISSUE TITLE
Module uses incompatible SDK version(v30) while v31 is required

### ISSUE THREAD

**Issue by StiviiK** [eisengrind/docker-altv-server#3] opened 2020-05-10 14:53 UTC
```
▶ docker run -it --rm eisengrind/altv-server:release-dotnet
[14:53:21] alt:V Server, build #1181, branch release
[14:53:21][Error] Vehicle mods can't be loaded.
[14:53:21][Error] Vehicle models can't be loaded.
[14:53:21] Starting Alt:V Server on Docker! on 0.0.0.0:7788
[14:53:21][Error] Failed to load module modules/libcsharp-module.so
	 Module uses incompatible SDK version(v30) while v31 is required
[14:53:21] Starting HTTP server on 0.0.0.0:7788
[14:53:21] Server started
^C[14:53:23] Server shutdown
```

**Comment by pixlcrashr** [comment] 2020-05-10 16:33
This problem is caused by asynchronous updates of the different alt:V dependencies. The current program which triggers the current releases only checks for the altv-server binary updates.

Though, the Docker Image should be fixed for now (I've re-triggered the latest release).

**Comment by pixlcrashr** [comment] 2020-06-16 14:39
Now, a program watches for server and module changes. This problem should not occur anymore.

**Closed as completed by pixlcrashr** 2020-06-16 14:39 UTC
Labels: bug
